# action.yml
name: 'ROS2 Environment'
description: 'Define target distribution'
inputs:
  ros-distribution:  # id of input
    description: 'ROS2 EoL Distribution'
    required: true
    default: 'foxy'
  use-cuda:
    description: 'Use CUDA environment'
    required: true
    default: true
  workspace_dir:
    description: 'List of Packages'
    required: true
    default: 'colcon_ws'
outputs:
  ros-workspace-directory-name:
    description: |
      root directory name of the ROS workspace created for this CI code.
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ros-distribution }}
    - ${{ inputs.workspace_dir }}